name: teste

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
 acao_inicial_job:
   runs-on: ubuntu-latest
   steps:
   - name: print resultado
     run: echo "deu certoooo"
   - name: print encerramento
     run: echo "finalizado"
     
     
   
